# Actividad 3 - Análisis numérico con pandas
## Juan Manuel González Ascencio - A00572003

In [3]:
import numpy as np
import pandas as pd 

In [6]:
# cargamos la información a una matriz de numpy
def leer_datos():
    data = pd.read_csv('DatosAutos-1-1.csv')
    data = data.to_numpy()
    return data

def main ():
    data = leer_datos()
    print(data)
main()

[[2.017e+03 1.200e+04 1.000e+00 ... 1.500e+02 5.770e+01 1.000e+00]
 [2.018e+03 1.400e+04 2.000e+00 ... 1.500e+02 5.770e+01 1.000e+00]
 [2.017e+03 1.300e+04 2.000e+00 ... 1.500e+02 5.770e+01 1.000e+00]
 ...
 [2.015e+03 9.999e+03 2.000e+00 ... 2.000e+01 6.730e+01 1.600e+00]
 [2.018e+03 8.299e+03 2.000e+00 ... 1.450e+02 5.770e+01 1.200e+00]
 [2.015e+03 8.299e+03 2.000e+00 ... 2.200e+01 5.770e+01 1.000e+00]]


La primera fase requiere que extraigas los siguientes datos:

NOTA: Realiza cada función con su main en un bloque de código distinto:

- Define la función precio_maximo, que regrese el precio máximo de un automóvil.
- Define la función promedio_impuestos, que regrese el promedio de impuestos (tax) pagados por ese lote de automóviles. Imprime en el main el resultado de la función promedio_impuestos con dos decimales.
- Define la función suma_millaje, que regrese la suma del millaje (mileage) del lote de autos. Imprime en el main el resultado de la función suma_millage con un decimal.
- Define la función cantidad_autos, que imprima la cantidad de autos de cada año.
- Define la función promedio_mpg, que regresa el promedio de millaje por galón (mpg) de cada tipo de combustible.

In [8]:
# Define la función precio_maximo, que regrese el precio máximo de un automóvil.

def precio_maximo(data):
    return data[:,1].max()

def main ():
    data = leer_datos()
    print(precio_maximo(data))

main()


54995.0


In [9]:
# Define la función promedio_impuestos, que regrese el promedio de impuestos (tax) pagados por ese lote de automóviles. Imprime en el main el resultado de la función promedio_impuestos con dos decimales.

def promedio_impuestos(data):
    return data[:,5].mean()

def main ():
    data = leer_datos()
    print(promedio_impuestos(data))

main()

113.3107115020599


In [11]:
#Define la función suma_millaje, que regrese la suma del millaje (mileage) del lote de autos. Imprime en el main el resultado de la función suma_millage con un decimal.

def suma_millaje(data):
    return data[:,3].sum()

def main (): 
    data = leer_datos()
    print(suma_millaje(data))

main()


419547822.0


In [13]:
#Define la función cantidad_autos, que imprima la cantidad de autos de cada año.

def cantidad_autos(data):
    autos = data[:,0]
    autos = np.unique(autos)
    for i in autos:
        print(i," - ", np.sum(data[:,0] == i))

def main ():
    data = leer_datos()
    cantidad_autos(data)

main()


2002.0  -  3
2003.0  -  3
2004.0  -  4
2005.0  -  16
2006.0  -  13
2007.0  -  32
2008.0  -  57
2009.0  -  91
2010.0  -  67
2011.0  -  94
2012.0  -  115
2013.0  -  609
2014.0  -  805
2015.0  -  1368
2016.0  -  2331
2017.0  -  4888
2018.0  -  4014
2019.0  -  3194
2020.0  -  258


In [23]:
#define la función promedio_mpg, que regresa el promedio de millaje por galón (mpg) de cada tipo de combustible.

def promedio_mpg(data):
    fuelType = {1: "Diesel", 2: "Electrico", 3: "Hibrido", 4: "Otro", 5: "Gasolina"}
    combustible = data[:,4]
    combustible = np.unique(combustible)
    for i in combustible:
        print(i,", ",fuelType[i]," - ", np.mean(data[data[:,4] == i][:,3]))

def main ():
    data = leer_datos()
    promedio_mpg(data)

main()

1.0 ,  Diesel  -  30663.064560916348
2.0 ,  Electrico  -  16963.5
3.0 ,  Hibrido  -  22602.0
4.0 ,  Otro  -  19470.0
5.0 ,  Gasolina  -  19902.801067761808


- La segunda fase es una comparativa. Para ello debes crear tres matrices de datos, una para los datos del año 2011, 2016 y 2018. Cada matriz debe contener la siguiente estructura:
    - Las filas o renglones representan el tipo de transmisión.
    - Las columnas representan: mpg promedio, el tamaño de motor más grande y la suma de los impuestos .
  Define la función calculos, que realice los cálculos anteriores.      
- Define la función calculos, que realice los cálculos anteriores.      
- Define la función imprime_matriz, que imprima la matriz con el siguiente formato:

In [50]:


def calculos(data, año, ):
    lista_transmission = [1,2,3]
    matrizFin=[]

    for i in lista_transmission:
        lista = []
        condicion = (data[:,2] == i) & (data[:,0] == año)
        matriz = data[condicion]
        arreglo = matriz[:,6]

        #promedio MGP
        if len(arreglo) > 0:
            promedio = np.mean(arreglo)
        else:
            promedio = 0

        lista.append(promedio)

        #motor más grande
        arreglo = matriz[:,7]
        if len(arreglo) > 0:
            motor = np.max(arreglo)
        else:
            motor = 0

        lista.append(motor)

        #suma de impuestos
        arreglo = matriz[:,5]
        if len(arreglo) > 0:
            impuestos = np.sum(arreglo)
        else:
            impuestos = 0

        lista.append(impuestos)
        matrizFin.append(lista)


    return matrizFin


def imprime_matriz(m):
    lista_año = ["Automático", "Manual", "Semi-auto"]
    cont  = 0
    print("\tMPG promedio\tMotor más grande\t Suma de impuestos")
    #print("m shape",m.shape[0])
    for i in range(m.shape[0]):
        print(lista_año[cont], end=" ")
        cont += 1
        for j in range(m.shape[1]):
            print("    \t%2f"% m[i,j], end=" ")
        print()



def main():
    print("Año 2011")
    data = leer_datos()
    año = 2011
    m = calculos(data, año)
    m = np.array(m)
    imprime_matriz(m)

    print("\n Año 2016")
    año = 2016
    m = calculos(data, año)
    m = np.array(m)
    imprime_matriz(m)

    print("\n Año 2018")
    año = 2018
    m = calculos(data, año)
    m = np.array(m)
    imprime_matriz(m)




main()



Año 2011
	MPG promedio	Motor más grande	 Suma de impuestos
Automático     	45.158333     	2.000000     	2370.000000 
Manual     	50.685366     	2.500000     	11075.000000 
Semi-auto     	0.000000     	0.000000     	0.000000 

 Año 2016
	MPG promedio	Motor más grande	 Suma de impuestos
Automático     	52.337500     	5.000000     	27070.000000 
Manual     	62.434859     	5.000000     	106585.000000 
Semi-auto     	53.080247     	5.000000     	18530.000000 

 Año 2018
	MPG promedio	Motor más grande	 Suma de impuestos
Automático     	49.501402     	5.000000     	31155.000000 
Manual     	59.580409     	5.000000     	527580.000000 
Semi-auto     	52.221547     	5.000000     	26440.000000 
