# Actividad 21 - Arreglos
## Juan Manuel González Ascencio - A00572003

-----------------------

- Genere un arreglo de Numpy de puros ceros de tipo de dato "int" de 30 elementos. Imprime el arreglo.
- Genere un arreglo de Numpy con 40 elementos de tipo float sin inicializar. Usa la función empty. Imprime el arreglo.
- Genere un arreglo de Numpy con números que vayan del 10 al 20. Usa la función arange(). Imprime el arreglo.
- Genere un arreglo de Numpy con números entre 1 y 30 con incrementos de 4, es decir: [1 5 9....]. Usa la función arange(). Imprime el arreglo.
- Genere un arreglo de Numpy con 10 elementos de tipo float entre 10 y 30 igualmente espaciados. Usa la función linspace. Imprime el arreglo.
- Genera un arreglo de Numpy llamado arreglo1 con 6 números aleatorios enteros entre 5 y 15  y genera otro arreglo llamado arreglo2 con 8 números aleatorios enteros entre 30 y 50. Concatena ambos arreglos en un arreglo llamado arreglo3. Imprime los tres arreglos.

In [1]:
import numpy as np

In [7]:
# Genere un arreglo de Numpy de puros ceros de tipo de dato "int" de 30 elementos. Imprime el arreglo.
arr = np.zeros(30, dtype=int)
print(arr)

#Genere un arreglo de Numpy con 40 elementos de tipo float sin inicializar. Usa la función empty. Imprime el arreglo.
arr2 = np.empty(40, dtype=float)
print(arr2)

#Genere un arreglo de Numpy con números entre 1 y 30 con incrementos de 4, es decir: [1 5 9....]. Usa la función arange(). Imprime el arreglo.

arr3 = np.arange(1, 30, 4)
print(arr3)

#Genere un arreglo de Numpy con 10 elementos de tipo float entre 10 y 30 igualmente espaciados. Usa la función linspace. Imprime el arreglo.
arr4 = np.linspace(10, 30, 10, dtype=float)
print(arr4)

#Genera un arreglo de Numpy llamado arreglo1 con 6 números aleatorios enteros entre 5 y 15  y genera otro arreglo llamado arreglo2 con 8 números aleatorios enteros entre 30 y 50. Concatena ambos arreglos en un arreglo llamado arreglo3. Imprime los tres arreglos.

arreglo1 = np.random.randint(5, 15, 6)
arreglo2 = np.random.randint(30, 50, 8)
arreglo3 = np.concatenate((arreglo1, arreglo2))
print(arreglo1)
print(arreglo2)
print(arreglo3)



[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[4.67402339e-310 0.00000000e+000 6.92107392e-310 6.92107540e-310
 6.92107502e-310 6.92107492e-310 6.92107492e-310 6.92107492e-310
 6.92107697e-310 6.92107502e-310 6.92107502e-310 6.92107500e-310
 6.92107502e-310 6.92107694e-310 6.92107697e-310 6.92107502e-310
 6.92107490e-310 6.92107502e-310 6.92107696e-310 6.92107694e-310
 6.92107696e-310 6.92107502e-310 6.92107488e-310 6.92107502e-310
 6.92107697e-310 6.92107696e-310 6.92107696e-310 6.92107697e-310
 6.92107697e-310 6.92107545e-310 6.92107539e-310 6.92107492e-310
 6.92107633e-310 6.92107697e-310 6.92107492e-310 2.16282177e-319
 7.24462626e-314 5.90257878e+250 4.44659081e-323 2.43034830e-313]
[ 1  5  9 13 17 21 25 29]
[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]
[ 9  6  6  9 10  7]
[45 34 31 43 35 38 48 32]
[ 9  6  6  9 10  7 45 34 31 43 35 38 48 32]


In [13]:
#Crea la función suma_impares que recibe un arreglo de números enteros. Utiliza el ciclo for para recorrer todo el arreglo. La función regresa la suma de todos los elementos impares del arreglo.

def suma_impares(arr):
    suma = 0
    for i in arr:
        if i % 2 != 0:
            suma = suma + i
    return suma

def main():
    arreglo = np.random.randint(-5,12,10)
    print(arreglo)
    print(suma_impares(arreglo))

main()



[ 1  6  9  9 -3 11  7  9  4 10]
43


In [15]:
#Crea la función multiplica_arreglo que recibe un arreglo de números enteros y un valor entero x. La función debe de multiplicar cada localidad del arreglo por x y el resultado de la multiplicación asignarla a su respectiva casilla. Utiliza el ciclo for para recorrer todo el arreglo

def multiplica_arreglo(arr, x):
    for i in range(len(arr)):
        arr[i] = arr[i] * x
    return arr

def main():
    arreglo = np.random.randint(-5,12,10)
    print(arreglo)
    x = int(input("Dame un número entero: "))
    print(multiplica_arreglo(arreglo, x))  

main()



[ 9  7  5 -5  1 -3 10  0  5  6]
[ 18  14  10 -10   2  -6  20   0  10  12]


In [16]:
#Crea la función cuenta_multiplos que recibe un arreglo de números enteros y un valor entero x. La función deberá regresar el resultado de contar todos los elementos múltiplos de x contenidos en el arreglo. NOTA: Los valores negativos no son contemplados. Utiliza el ciclo for para recorrer todo el arreglo.

def cuenta_multiplos(arr, x):
    contador = 0
    for i in arr:
        if i % x == 0 and i > 0:
            contador += 1
    return contador

def main():
    arreglo = np.random.randint(-5,12,10)
    print(arreglo)
    x = int(input("Dame un número entero: "))
    print(cuenta_multiplos(arreglo, x))

main()


[ 4  6 -5  9 -1  4  3  0  7 11]
3
